- name: Add the bonding module
  modprobe:
    name: bonding
    state: present

- name: add ifenslave package
  package:
    name: ifenslave
    state: present

- name: set up network interfaces
  template:
    src: bonded-interfaces.j2
    dest: /etc/network/interfaces
  notify: restart networking
  register: interface_updated

- name: Send the reboot command
  command: shutdown -r now
  async: 0
  poll: 0
  when: interface_updated | changed

- name: Wait for server to come back
  wait_for_connection:
    timeout: 900