---

- name: libvirtd.conf file
  copy:
    src: libvirtd.conf
    dest: /etc/libvirt/libvirtd.conf
  notify: restart libvirt-bin

- name: qemu.conf file
  copy:
    src: qemu.conf
    dest: /etc/libvirt/qemu.conf
  notify: restart libvirt-bin

