---
- name: Install virt groupinstall on RHEL systems
  yum:
    name: "{{ kvm_libvirt_group_installs }}"
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ( kvm_libvirt_group_installs|length ) > 0

- name: Install libvirt packages and dependencies
  package:
    name: "{{ kvm_libvirt_pkgs }}"
    state: present

- name: "Install all Python requirements via Pip"
  pip:
    name: "{{ kvm_python_pkgs }}"
    state: present
  when: ( kvm_python_pkgs|length ) > 0

