---
- name: Install libvirt packages and dependencies
  package:
    name: "{{ libvirt_pkgs }}"
    state: present

- name: "Install all Python2 requirements via Pip"
  pip:
    name: "{{ kvm_python_pkgs }}"
    state: latest
    executable: pip2
  when: kvm_python_pkgs is defined

- name: "Install all Python3 requirements via Pip"
  pip:
    name: "{{ kvm_python3_pkgs }}"
    state: latest
    executable: pip3
  when: kvm_python3_pkgs is defined

- name: /etc/default/libvirtd
  copy:
    src: libvirtd
    dest: /etc/default/libvirtd

- name: enable libvirtd service
  service:
    name: libvirtd
    enabled: yes
