---
- name: Install libvirt packages and dependencies
  package:
    name: "{{ libvirt_pkgs }}"
    state: present

- name: /etc/default/libvirtd
  copy:
    src: libvirtd
    dest: /etc/default/libvirtd

- name: enable libvirtd service
  service:
    name: libvirtd
    enabled: yes
