---
- name: Install virt groupinstall on RHEL systems
  yum:
    name: "{{ libvirt_group_installs }}"
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Install libvirt packages and dependencies
  package:
    name: "{{ libvirt_pkgs }}"
    state: present

- name: "Install all Python requirements via Pip"
  pip:
    name: "{{ kvm_python_pkgs }}"
    state: latest
  when: kvm_python_pkgs is defined

- name: /etc/default/libvirtd
  copy:
    src: libvirtd
    dest: /etc/default/libvirtd

- name: enable and start libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes
