---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- import_tasks: installation.yml
  tags:
    - kvm-guests

- import_tasks: configuration.yml

- meta: flush_handlers

- name: enable and start or restart libvirt service
  service:
    name: "{{ kvm_libvirt_service }}"
    state: "{% if libvirt_requires_restart %}restarted{% else %}started{% endif %}"
    enabled: yes


- import_tasks: config_vm_network.yml
  tags:
    - kvm-network

- import_tasks: config_vm_storage.yml
  tags:
    - kvm-storage

- import_tasks: guests.yml
  tags:
    - never
    - kvm-guests
