---
- name: restart libvirt service
  set_fact:
    libvirt_requires_restart: True

- name: restart networking
  set_fact:
    networking_requires_restart: True

- name: reconfigure networking
  set_fact:
    networking_requires_rebuild: True
